from fastapi import APIRouter, Request, HTTPException
import pandas as pd
import numpy as np

# Import validation schema
from schemas import PredictionRequest

router = APIRouter()

@router.post("/predict")
async def predict(
    request: Request,
    payload: PredictionRequest
):
    """
    Predict severity score and recommend officer count for a specific junction, hour, and day.
    """
    model = request.app.state.model
    encoder = request.app.state.encoder
    meta_df = request.app.state.meta_df
    grid_df = request.app.state.grid_df
    features = request.app.state.features

    junction = payload.junction
    hour = payload.hour
    day_of_week = payload.day_of_week

    # Find label encoding for junction name
    try:
        j_enc = int(encoder.transform([junction])[0])
    except ValueError:
        raise HTTPException(status_code=404, detail=f"Junction '{junction}' not found in encoder classes")

    # Retrieve metadata for junction
    j_meta = meta_df[meta_df["junction_name"] == junction]
    if j_meta.empty:
        raise HTTPException(status_code=404, detail=f"No metadata found for junction '{junction}'")

    # Look up the pre-computed XGBoost severity for this exact slot.
    # The grid was generated by the trained model with full junction-specific features —
    # it is the authoritative model output for known junction/hour/day combinations.
    grid_row = grid_df[
        (grid_df["junction_name"] == junction) &
        (grid_df["hour"] == hour) &
        (grid_df["day_of_week"] == day_of_week)
    ]

    if not grid_row.empty:
        severity = float(grid_row["predicted_severity"].iloc[0])
    else:
        # Fallback: run the live model for out-of-grid slots
        j_grid = grid_df[grid_df["junction_name"] == junction]
        j_base = j_grid.iloc[0] if not j_grid.empty else None
        feats = {
            "junction_encoded":  j_enc,
            "hour":              hour,
            "day_of_week":       day_of_week,
            "is_weekend":        int(day_of_week >= 5),
            "peak_bucket":       2 if hour <= 6 else (1 if hour >= 19 else 0),
            "main_road_pct":     float(j_base["main_road_pct"]) if j_base is not None else 0.02,
            "footpath_pct":      float(j_base["footpath_pct"]) if j_base is not None else 0.02,
            "near_junction_pct": float(j_base["near_junction_pct"]) if j_base is not None else 0.01,
            "two_wheeler_pct":   float(j_base["two_wheeler_pct"]) if j_base is not None else 0.45,
            "four_wheeler_pct":  float(j_base["four_wheeler_pct"]) if j_base is not None else 0.30,
            "commercial_pct":    float(j_base["commercial_pct"]) if j_base is not None else 0.18,
            "avg_viol_count":    float(j_base["avg_viol_count"]) if j_base is not None else 1.2,
            "is_historic_peak":  float(j_base["is_historic_peak"]) if j_base is not None else 0,
        }
        try:
            X = pd.DataFrame([feats])[features]
            pred_log = model.predict(X)[0]
            severity = float(np.expm1(pred_log))
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Model inference failed: {str(e)}")

    recommended_officers = max(1, min(5, round(severity / 14)))

    return {
        "junction": junction,
        "hour": hour,
        "day_of_week": day_of_week,
        "predicted_severity": round(severity, 2),
        "recommended_officers": recommended_officers
    }
